# Generated by Django 4.0.6 on 2024-03-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.CharField(default='BORRAR', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='modelo',
            field=models.CharField(default='BORRAR', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
