# Generated by Django 4.0.6 on 2024-04-02 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items_app', '0002_remove_item_name_item_marca_item_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
